Step 1: Import Libraries

In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report , confusion_matrix

Step 2: Load and Explore Data

For this example, we’ll use the Iris dataset, a classic dataset for classification.

In [5]:
from sklearn.datasets import load_iris

#load dataset
iris = load_iris()
X = iris.data   #features
Y = iris.target  #labels

#check the dataset
print("Feature Names: ", iris.feature_names)
print("Target Names: ", iris.target_names)
print("First 5 Rows of Data:\n",X[:5])
print("Target Labels:\n",Y[:5])


Feature Names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target Names:  ['setosa' 'versicolor' 'virginica']
First 5 Rows of Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Target Labels:
 [0 0 0 0 0]
